version: '3.5'

services:
  neo4j:
    container_name: neo4j-apoc
    image: neo4j:4.4.8-community
    ports:
    - 7474:7474
    - 7687:7687
    volumes:
    - $HOME/docker_data/neo4j/data:/data
    environment:
      - NEO4JLABS_PLUGINS=\[\"apoc\"\]
      #- NEO4J_apoc_export_file_enabled=true
      #- NEO4J_apoc_import_file_enabled=true
      #- NEO4J_apoc_import_file_use__neo4j__config=true

